version: '3.8'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - demo_net

  py:
    build: ./py
    container_name: py
    environment:
      - ES_HOST = "http://es:9200"
      - ES_INDEX = "demo"
    depends_on:
      - es
    networks:
      - demo_net

networks:
  demo_net:
    driver: bridge